### ISSUE TITLE
Failed to install - unable to compile dukpy [Unable to install package pytboss==2024.2.0]

### ISSUE THREAD

**Issue by cap60552** [dknowles2/pytboss#90]
When trying to install the latest version of the integration the install fails.  I see the following error which seems to indicate that the install is trying to compile a new version of dukpy, but gcc is not present in home assistant.

`Unable to install package pytboss==2024.2.0: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [144 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-x86_64-cpython-312 creating build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/tsc.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/run.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/nodelike.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/module_loader.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/lessc.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/install.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/evaljs.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/coffee.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/babel.py -> build/lib.linux-x86_64-cpython-312/dukpy copying dukpy/__init__.py -> build/lib.linux-x86_64-cpython-312/dukpy creating build/lib.linux-x86_64-cpython-312/dukpy/webassets copying dukpy/webassets/typescriptfilter.py -> build/lib.linux-x86_64-cpython-312/dukpy/webassets copying dukpy/webassets/lessfilter.py -> build/lib.linux-x86_64-cpython-312/dukpy/webassets copying dukpy/webassets/jsxfilter.py -> build/lib.linux-x86_64-cpython-312/dukpy/webassets copying dukpy/webassets/babelfilter.py -> build/lib.linux-x86_64-cpython-312/dukpy/webassets copying dukpy/webassets/__init__.py -> build/lib.linux-x86_64-cpython-312/dukpy/webassets creating build/lib.linux-x86_64-cpython-312/dukpy/jscore copying dukpy/jscore/url.js -> build/lib.linux-x86_64-cpython-312/dukpy/jscore copying dukpy/jscore/querystring.js -> build/lib.linux-x86_64-cpython-312/dukpy/jscore copying dukpy/jscore/punycode.js -> build/lib.linux-x86_64-cpython-312/dukpy/jscore copying dukpy/jscore/path.js -> build/lib.linux-x86_64-cpython-312/dukpy/jscore copying dukpy/jscore/fs.js -> build/lib.linux-x86_64-cpython-312/dukpy/jscore creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules copying dukpy/jsmodules/typescriptServices.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules copying dukpy/jsmodules/semver.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules copying dukpy/jsmodules/coffeescript.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules copying dukpy/jsmodules/babel-6.26.0.min.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/react copying dukpy/jsmodules/react/react.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/react copying dukpy/jsmodules/react/react-dom-server.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/react creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/url-file-manager.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/plugin-loader.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/lessc-helper.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/index.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/image-size.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/fs.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/file-manager.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node copying dukpy/jsmodules/less/less-node/environment.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less-node creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/utils.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/transform-tree.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/source-map-output.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/source-map-builder.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/render.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/plugin-manager.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/parse.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/parse-tree.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/logger.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/less-error.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/index.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/import-manager.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less copying dukpy/jsmodules/less/less/contexts.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/visitor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/to-css-visitor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/set-tree-visibility-visitor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/join-selector-visitor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/index.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/import-visitor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/import-sequencer.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors copying dukpy/jsmodules/less/less/visitors/extend-visitor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/visitors creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/variable.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/value.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/url.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/unit.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/unicode-descriptor.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/selector.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/ruleset.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/ruleset-call.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/rule.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/quoted.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/paren.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/operation.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/node.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/negative.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/mixin-definition.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/mixin-call.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/media.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/keyword.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/js-eval-node.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/javascript.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/index.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/import.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/extend.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/expression.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/element.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/directive.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/dimension.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/detached-ruleset.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/debug-info.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/condition.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/comment.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/combinator.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/color.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/call.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/attribute.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/assignment.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/anonymous.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree copying dukpy/jsmodules/less/less/tree/alpha.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/tree creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/plugins copying dukpy/jsmodules/less/less/plugins/function-importer.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/plugins creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/parser copying dukpy/jsmodules/less/less/parser/parser.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/parser copying dukpy/jsmodules/less/less/parser/parser-input.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/parser copying dukpy/jsmodules/less/less/parser/chunker.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/parser creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/types.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/svg.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/string.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/number.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/math.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/math-helper.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/index.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/function-registry.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/function-caller.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/default.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/data-uri.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/color.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions copying dukpy/jsmodules/less/less/functions/color-blending.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/functions creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/environment copying dukpy/jsmodules/less/less/environment/file-manager-api.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/environment copying dukpy/jsmodules/less/less/environment/environment.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/environment copying dukpy/jsmodules/less/less/environment/environment-api.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/environment copying dukpy/jsmodules/less/less/environment/abstract-file-manager.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/environment creating build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/data copying dukpy/jsmodules/less/less/data/unit-conversions.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/data copying dukpy/jsmodules/less/less/data/index.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/data copying dukpy/jsmodules/less/less/data/colors.js -> build/lib.linux-x86_64-cpython-312/dukpy/jsmodules/less/less/data running build_ext building 'dukpy._dukpy' extension creating build/temp.linux-x86_64-cpython-312 creating build/temp.linux-x86_64-cpython-312/src creating build/temp.linux-x86_64-cpython-312/src/duktape gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -DDUK_OPT_NONSTD_REGEXP_DOLLAR_ESCAPE=1 -DDUK_OPT_OCTAL_SUPPORT=1 -I./src/duktape -I/usr/local/include/python3.12 -c src/_support.c -o build/temp.linux-x86_64-cpython-312/src/_support.o error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for dukpy ERROR: Could not build wheels for dukpy, which is required to install pyproject.toml-based projects`

**Comment by dknowles2** [comment]
See https://github.com/dknowles2/ha-pitboss/issues/42
